#!/usr/bin/env bash
# Install Nginx, configure it to listen on port 80 and returns a page
# containing the string 'Hello World!' when queried with curl and redirect
# /redirect_me to another page
apt-get update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html index.htm;

	server_name ezekielogunewu.tech;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}
" > /etc/nginx/sites-available/default
service nginx restart
