#!/usr/bin/env bash
# Install Nginx, configure it to listen on port 80 and returns a page
# containing the string 'Hello World!' when queried with curl and redirect
# /redirect_me to another page
apt-get update
apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/var/www/html;
	index	index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
" > /etc/nginx/sites-available/default
service nginx restart
