#!/usr/bin/env bash
# Install and configure HAproxy so that it sends traffic to two servers using the roundrobin algorithm

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get install -y haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg{,.original}

printf %s "
frontend balancer
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 468530-web-01 18.214.89.20:80 check
	server 468530-web-02 52.203.53.113:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
