#!/usr/bin/env bash
# Displays To 'infinity and beyond' indefinitely and also catches the SIGTERM signal
function terminate {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminate' SIGTERM
trap 'terminate' SIGQUIT
i=1
while [ $i -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
