#!/usr/bin/env bash
# Displays To 'infinity and beyond' indefinitely and also catches the SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
i=1
while [ $i -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
