#!/usr/bin/env bash
# Loops from 1 to 10 and display Best School, bad luck at the 4th iterationn and good luck at the 8th iteration

i=1
while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	: $(( i++ ))
done
